# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_graph_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Graph(object):
    def setupUi(self, Graph):
        Graph.setObjectName("Graph")
        Graph.resize(406, 300)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Graph.sizePolicy().hasHeightForWidth())
        Graph.setSizePolicy(sizePolicy)
        self.graphLayout = QtWidgets.QVBoxLayout(Graph)
        self.graphLayout.setContentsMargins(0, 0, 0, 0)
        self.graphLayout.setObjectName("graphLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelNumberOfPoints = QtWidgets.QLabel(Graph)
        self.labelNumberOfPoints.setObjectName("labelNumberOfPoints")
        self.horizontalLayout.addWidget(self.labelNumberOfPoints)
        self.spinBoxNumberOfPoints = QtWidgets.QSpinBox(Graph)
        self.spinBoxNumberOfPoints.setMinimum(10)
        self.spinBoxNumberOfPoints.setMaximum(100)
        self.spinBoxNumberOfPoints.setProperty("value", 30)
        self.spinBoxNumberOfPoints.setObjectName("spinBoxNumberOfPoints")
        self.horizontalLayout.addWidget(self.spinBoxNumberOfPoints)
        self.labelIntervall = QtWidgets.QLabel(Graph)
        self.labelIntervall.setObjectName("labelIntervall")
        self.horizontalLayout.addWidget(self.labelIntervall)
        self.spinBoxIntervall = QtWidgets.QSpinBox(Graph)
        self.spinBoxIntervall.setMinimum(1)
        self.spinBoxIntervall.setMaximum(3600)
        self.spinBoxIntervall.setProperty("value", 5)
        self.spinBoxIntervall.setObjectName("spinBoxIntervall")
        self.horizontalLayout.addWidget(self.spinBoxIntervall)
        self.buttonApply = QtWidgets.QPushButton(Graph)
        self.buttonApply.setObjectName("buttonApply")
        self.horizontalLayout.addWidget(self.buttonApply)
        self.graphLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Graph)
        QtCore.QMetaObject.connectSlotsByName(Graph)

    def retranslateUi(self, Graph):
        _translate = QtCore.QCoreApplication.translate
        Graph.setWindowTitle(_translate("Graph", "Form"))
        self.labelNumberOfPoints.setText(_translate("Graph", "Number of Points"))
        self.labelIntervall.setText(_translate("Graph", "Intervall [s]"))
        self.buttonApply.setText(_translate("Graph", "Apply"))
